### ISSUE TITLE
Error in spliceai10k(input, refseq.table): argument "genome" is missing

### ISSUE THREAD

**Issue by gilberto-dagente** [emunte/vaRHC#4]
I keep getting an error, any suggestions?

Thanks, Gilberto

INPUT
eg.gene <- "DDX53"
eg.variant <- "c.1143G>T"

dir <- "/home/jupyter"
ref  <- "/home/jupyter/Homo_sapiens_assembly38.fasta"

var.information <- vaR(gene = eg.gene, variant = eg.variant, provean.program = TRUE, provean.sh = "/usr/local/bin/provean.sh", spliceai.10k= TRUE, spliceai.program = TRUE, spliceai.referenc = "/home/jupyter/Homo_sapiens_assembly38.fasta", spliceai.annotation = "/home/jupyter/Align/grch38.txt", output.dir = dir,  verbose = TRUE)

OUTPUT

looking for VariantInfo, please wait
0% completed ... correcting variant nomenclature 
10% completed ... getting variant coordinates
15% completed ... extracting bbdd information
20% completed ... getting information from gnomAD
30% completed ... getting information from flossiesdb
40% completed ... getting clinVar information
50% completed ... getting predictors information
Scanning file to determine attributes.
File attributes:
  meta lines: 29
  header_line: 30
  variant count: 1
  column count: 8
Meta line 29 read in.
All meta lines processed.
gt matrix initialized.
Character matrix gt created.
  Character matrix gt rows: 1
  Character matrix gt cols: 8
  skip: 0
  nrows: 1
  row_num: 0
Processed variant: 1
All variants processed
Error in spliceai10k(input, refseq.table): argument "genome" is missing, with no default
Traceback:

1. vaR(gene = eg.gene, variant = eg.variant, provean.program = TRUE, 
 .     provean.sh = "/usr/local/bin/provean.sh", spliceai.10k = TRUE, 
 .     spliceai.program = TRUE, spliceai.referenc = "/home/jupyter/Homo_sapiens_assembly38.fasta", 
 .     spliceai.annotation = "/home/jupyter/Align/grch38.txt", output.dir = dir, 
 .     verbose = TRUE)
2. vaRinfo(gene = gene, variant = variant, NM = NM, CCDS = CCDS, 
 .     gene.specific.df = gene.specific.df, output.dir = output.dir, 
 .     remote = remote, browser = browser, spliceai.program = spliceai.program, 
 .     spliceai.reference = spliceai.reference, spliceai.annotation = spliceai.annotation, 
 .     spliceai.distance = spliceai.distance, spliceai.masked = spliceai.masked, 
 .     provean.program = provean.program, provean.sh = provean.sh, 
 .     spliceai.10k = spliceai.10k, google.search = google.search, 
 .     verbose = verbose)
3. predicInfo(object = variant.info, gene.specific = gene.specific, 
 .     bbdd = bbdd.info, gnomad = gnom, output.dir = output.dir, 
 .     spliceai.program = spliceai.program, spliceai.reference = spliceai.reference, 
 .     spliceai.annotation = spliceai.annotation, spliceai.distance = spliceai.distance, 
 .     spliceai.masked = spliceai.masked, provean.program = provean.program, 
 .     provean.sh = provean.sh, spliceai.10k = spliceai.10k, verbose = verbose)
4. spliceaiR(object = object, ext.spliceai = gnomad, output.dir = output.dir, 
 .     bbdd = bbdd, spliceai.program = spliceai.program, reference.splice = spliceai.reference, 
 .     annotation.splice = spliceai.annotation, distance = spliceai.distance, 
 .     mask = spliceai.masked, verbose = verbose, spliceai.10k = spliceai.10k)
5. spliceai10k(input, refseq.table)
6. ifelse(genome == 37, "hg19", "hg38")

**Comment by emunte** [comment]
Dear Gilberto,
Thanks for your feedback.
Let me take a look and I will get back to you  ASAP.

Eli

**Comment by emunte** [comment]
Dear Gilberto,
Thank you for bringing this to our attention. I have addressed the reported bug and made the necessary fixes. To verify the resolution, please follow these steps:
```
INPUT
eg.gene <- "DDX53"
eg.variant <- "c.1143G>T"

dir <- "/home/jupyter"
ref <- "/home/jupyter/Homo_sapiens_assembly38.fasta"
var.information <- vaR(gene = eg.gene, variant = eg.variant, provean.program = TRUE, provean.sh = "/usr/local/bin/provean.sh", spliceai.10k= TRUE, spliceai.program = TRUE, **spliceai.genome= "hg38",** spliceai.reference = "/home/jupyter/Homo_sapiens_assembly38.fasta", spliceai.annotation = "/home/jupyter/Align/grch38.txt", output.dir = dir, verbose = TRUE)
```

Please reinstall vaRHC and run the provided code. Let me know if you encounter any issues.

Thank you for your patience and cooperation.

Best regards,

Eli

**Comment by emunte** [comment]
Dear Gilberto,
Thank you for bringing this to our attention. I have addressed the reported bug and made the necessary fixes. To verify the resolution, please follow these steps:
```

INPUT
eg.gene <- "DDX53"
eg.variant <- "c.1143G>T"

dir <- "/home/jupyter"
ref <- "/home/jupyter/Homo_sapiens_assembly38.fasta"
var.information <- vaR(gene = eg.gene, variant = eg.variant, provean.program = TRUE, provean.sh = "/usr/local/bin/provean.sh", spliceai.10k= TRUE, spliceai.program = TRUE, spliceai.genome= "hg38", spliceai.reference = "/home/jupyter/Homo_sapiens_assembly38.fasta", spliceai.annotation = "/home/jupyter/Align/grch38.txt", output.dir = dir, verbose = TRUE)
```

Please reinstall vaRHC and run the provided code. Let me know if you encounter any issues.

Thank you for your patience and cooperation.

Best regards,

Eli

**Comment by gilberto-dagente** [comment]
Hi Elisabet,

 

I’m getting another error from the input code you provided. Im also getting an error from the example provided in the documents (it was previously working).

 

Thanks for any help you can provide.

 

-Gilberto

 
INPUT
eg.gene <- "DDX53"
eg.variant <- "c.1143G>T"
 
dir <- "/home/jupyter"
ref <- "/home/jupyter/Homo_sapiens_assembly38.fasta"
var.information <- vaR(gene = eg.gene, variant = eg.variant, provean.program = TRUE, provean.sh = "/usr/local/bin/provean.sh", spliceai.10k= TRUE, spliceai.program = TRUE, spliceai.genome= "hg38", spliceai.reference = "/home/jupyter/Homo_sapiens_assembly38.fasta", spliceai.annotation = "/home/jupyter/Align/grch38.txt", output.dir = dir, verbose = TRUE)

 

OUTPUT

looking for VariantInfo, please wait

0% completed ... correcting variant nomenclature 

10% completed ... getting variant coordinates

15% completed ... extracting bbdd information

20% completed ... getting information from gnomAD

30% completed ... getting information from flossiesdb

40% completed ... getting clinVar information

50% completed ... getting predictors information

Scanning file to determine attributes.

File attributes:

  meta lines: 29

  header_line: 30

  variant count: 1

  column count: 8

Meta line 29 read in.

All meta lines processed.

gt matrix initialized.

Character matrix gt created.

  Character matrix gt rows: 1

  Character matrix gt cols: 8

  skip: 0

  nrows: 1

  row_num: 0

Processed variant: 1

All variants processed

 

Prepare transcripts

Error in spliceaiR(object = object, ext.spliceai = gnomad, output.dir = output.dir,  : 

  object 'refseq.table' not found

Error: Transcript not listed in SpliceAI annotation file. Please provide another annotation file if you want to compute this variant

Traceback:

 

1. vaR(gene = eg.gene, variant = eg.variant, provean.program = TRUE, 

 .     provean.sh = "/usr/local/bin/provean.sh", spliceai.10k = TRUE, 

 .     spliceai.program = TRUE, spliceai.genome = "hg38", spliceai.reference = "/home/jupyter/Homo_sapiens_assembly38.fasta", 

 .     spliceai.annotation = "/home/jupyter/Align/grch38.txt", output.dir = dir, 

 .     verbose = TRUE)

2. vaRinfo(gene = gene, variant = variant, NM = NM, CCDS = CCDS, 

 .     gene.specific.df = gene.specific.df, output.dir = output.dir, 

 .     remote = remote, browser = browser, spliceai.program = spliceai.program, 

 .     spliceai.genome = spliceai.genome, spliceai.reference = spliceai.reference, 

 .     spliceai.annotation = spliceai.annotation, spliceai.distance = spliceai.distance, 

 .     spliceai.masked = spliceai.masked, provean.program = provean.program, 

 .     provean.sh = provean.sh, spliceai.10k = spliceai.10k, google.search = google.search, 

 .     verbose = verbose)

3. predicInfo(object = variant.info, gene.specific = gene.specific, 

 .     bbdd = bbdd.info, gnomad = ifelse(genome == 37, gnom, gnom.hg38), 

 .     genome = genome, output.dir = output.dir, spliceai.program = spliceai.program, 

 .     spliceai.reference = spliceai.reference, spliceai.annotation = spliceai.annotation, 

 .     spliceai.distance = spliceai.distance, spliceai.masked = spliceai.masked, 

 .     provean.program = provean.program, provean.sh = provean.sh, 

 .     spliceai.10k = spliceai.10k, verbose = verbose)

4. spliceaiR(object = object, ext.spliceai = gnomad, output.dir = output.dir, 

 .     bbdd = bbdd, spliceai.program = spliceai.program, reference.splice = spliceai.reference, 

 .     annotation.splice = spliceai.annotation, distance = spliceai.distance, 

 .     mask = spliceai.masked, verbose = verbose, spliceai.10k = spliceai.10k, 

 .     genome = genome)

5. assertthat::assert_that(length(spliceai.score) != 0, msg = "Transcript not listed in SpliceAI annotation file. Please provide another annotation file if you want to compute this variant")

 

INPUT

eg.gene <- "CDH1"

eg.variant <- "c.1137+1G>A"

var.information <- vaR(gene = eg.gene, variant = eg.variant)

 

OUTPUT

looking for VariantInfo, please wait

0% completed ... correcting variant nomenclature 

10% completed ... getting variant coordinates

15% completed ... extracting bbdd information

20% completed ... getting information from gnomAD

30% completed ... getting information from flossiesdb

40% completed ... getting clinVar information

Error in !is.na(page) && !is.null(page) && class(page) != "try-error": 'length = 2' in coercion to 'logical(1)'

Traceback:

 

1. vaR(gene = eg.gene, variant = eg.variant)

2. vaRinfo(gene = gene, variant = variant, NM = NM, CCDS = CCDS, 

 .     gene.specific.df = gene.specific.df, output.dir = output.dir, 

 .     remote = remote, browser = browser, spliceai.program = spliceai.program, 

 .     spliceai.genome = spliceai.genome, spliceai.reference = spliceai.reference, 

 .     spliceai.annotation = spliceai.annotation, spliceai.distance = spliceai.distance, 

 .     spliceai.masked = spliceai.masked, provean.program = provean.program, 

 .     provean.sh = provean.sh, spliceai.10k = spliceai.10k, google.search = google.search, 

 .     verbose = verbose)

3. clinVarInfo(clinvar.ids, object = variant.info, verbose = verbose)

4. clinVarTable(clinvar.ids, verbose = verbose)

5. lapply(table$url, function(g, verbose) {

.     page <- try(readUrl(g))

.     if (!is.na(page) && !is.null(page) && class(page) != "try-error" && 

 .         any(class(page[1]) != "try-error")) {

.         table.ex <- rvest::html_table(page, fill = TRUE)

.         colnames(table.ex[[4]]) <- c("Interpretation", "Review_status", 

 .             "Condition", "Submitter", "More_information", "more")

.         interpret <- table.ex[[4]][1] %>% as.data.frame() %>% 

 .             dplyr::mutate(Interpretation = purrr::map(stringr::str_split(.data$Interpretation, 

 .                 \\n <file://n> ), 1))

.         date.clin <- table.ex[[4]][1] %>% as.data.frame() %>% 

 .             dplyr::mutate(date = purrr::map(stringr::str_split(.data$Interpretation, 

 .                 "\\(|\\)"), 2))

.         review <- table.ex[[4]][2] %>% as.data.frame() %>% dplyr::mutate(review = purrr::map(stringr::str_split(.data$Review_status, 

 .             \\n <file://n> ), 1)) %>% dplyr::select("review")

.         review.mode <- table.ex[[4]][2] %>% as.data.frame() %>% 

 .             dplyr::mutate(review2 = purrr::map(stringr::str_split(.data$Review_status, 

 .                 \\n <file://n> ), 3)) %>% dplyr::select("review2")

.         table.ex[[4]][1] <- unlist(interpret$Interpretation)

.         table.ex[[4]][2] <- unlist(review)

.         table.ex[[4]][6] <- unlist(date.clin$date)

.         table.ex[[4]]$review_mode <- unlist(review.mode)

.         table.ex[[4]] <- table.ex[[4]] %>% dplyr::rowwise() %>% 

 .             dplyr::mutate(More_information = stringr::str_replace_all(.data$More_information, 

 .                 "\n", "") %>% stringr::str_replace_all("  ", 

 .                 ""), Condition = stringr::str_replace_all(.data$Condition, 

 .                 "\n", ""))

.         summary <- reviewStatus(as.data.frame(table.ex[[4]]))

.         text.ex <- rvest::html_nodes(page, "dd")

.         interpret <- stringr::str_replace_all(rvest::html_text(text.ex)[1], 

 .             "  |\\n", "")

.         status <- stringr::str_replace_all(rvest::html_text(text.ex)[2], 

 .             "  |\\n", "")

.         submissions <- stringr::str_replace_all(rvest::html_text(text.ex)[3], 

 .             "  |\\n", "")

.         mix <- data.frame(interpret = interpret, status = status, 

 .             submissions = submissions)

.         table.ex$mix <- mix

.         table.ex[["summary"]] <- summary

.         return(table.ex)

.     }

. })

6. FUN(X[[i]], ...)

**Comment by emunte** [comment]
Dear Gilberto,

Thank you once again for your feedback.
Could you please test two things?
Firstly, try using the same parameters but with spliceai.10k=FALSE. I want to check if the issue is specific to that setting.
```
eg.gene <- "DDX53"
eg.variant <- "c.1143G>T"

dir <- "/home/jupyter"
ref <- "/home/jupyter/Homo_sapiens_assembly38.fasta"
var.information <- vaR(gene = eg.gene, variant = eg.variant, provean.program = TRUE, provean.sh = "/usr/local/bin/provean.sh", spliceai.10k= FALSE, spliceai.program = TRUE, spliceai.genome= "hg38", spliceai.reference = "/home/jupyter/Homo_sapiens_assembly38.fasta", spliceai.annotation = "/home/jupyter/Align/grch38.txt", output.dir = dir, verbose = TRUE)

```

Secondly, could you please use the same parameters but without specifying the spliceai.annotation parameter?

```
eg.gene <- "DDX53"
eg.variant <- "c.1143G>T"

dir <- "/home/jupyter"
ref <- "/home/jupyter/Homo_sapiens_assembly38.fasta"
var.information <- vaR(gene = eg.gene, variant = eg.variant, provean.program = TRUE, provean.sh = "/usr/local/bin/provean.sh", spliceai.10k= TRUE, spliceai.program = TRUE, spliceai.genome= "hg38", spliceai.reference = "/home/jupyter/Homo_sapiens_assembly38.fasta", output.dir = dir, verbose = TRUE)

```
Regarding the example, I attempted to rerun it, and it worked on my PC. Could you please rerun it using the vaRbatch function and share the log file with me? The log file will be generated in the "dir" folder, within a subfolder named "log."

```

eg.gene <- "CDH1"
eg.variant <- "c.1137+1G>A"
var.information <- vaRbatch(data.frame(gene = eg.gene, variant = eg.variant),  provean.program = FALSE, spliceai.10k= FALSE, spliceai.program = FALSE, excel.results = TRUE, output.dir = dir, verbose = TRUE)

```
Thanks for your time,
Best regards

Eli

**Comment by gilberto-dagente** [comment]
Hey Eli,

 

Thanks for the quick response. Your second suggestion worked, but the example still failed (output below and log file attached.)

 

Thanks for all your help.

 

-G

 

OUTPUT 1

 

Error: Transcript not listed in SpliceAI annotation file. Please provide another annotation file if you want to compute this variant

Traceback:

 

1. vaR(gene = eg.gene, variant = eg.variant, provean.program = TRUE, 

 .     provean.sh = "/usr/local/bin/provean.sh", spliceai.10k = FALSE, 

 .     spliceai.program = TRUE, spliceai.genome = "hg38", spliceai.reference = "/home/jupyter/Homo_sapiens_assembly38.fasta", 

 .     spliceai.annotation = "/home/jupyter/Align/grch38.txt", output.dir = dir, 

 .     verbose = TRUE)

2. vaRinfo(gene = gene, variant = variant, NM = NM, CCDS = CCDS, 

 .     gene.specific.df = gene.specific.df, output.dir = output.dir, 

 .     remote = remote, browser = browser, spliceai.program = spliceai.program, 

 .     spliceai.genome = spliceai.genome, spliceai.reference = spliceai.reference, 

 .     spliceai.annotation = spliceai.annotation, spliceai.distance = spliceai.distance, 

 .     spliceai.masked = spliceai.masked, provean.program = provean.program, 

 .     provean.sh = provean.sh, spliceai.10k = spliceai.10k, google.search = google.search, 

 .     verbose = verbose)

3. predicInfo(object = variant.info, gene.specific = gene.specific, 

 .     bbdd = bbdd.info, gnomad = ifelse(genome == 37, gnom, gnom.hg38), 

 .     genome = genome, output.dir = output.dir, spliceai.program = spliceai.program, 

 .     spliceai.reference = spliceai.reference, spliceai.annotation = spliceai.annotation, 

 .     spliceai.distance = spliceai.distance, spliceai.masked = spliceai.masked, 

 .     provean.program = provean.program, provean.sh = provean.sh, 

 .     spliceai.10k = spliceai.10k, verbose = verbose)

4. spliceaiR(object = object, ext.spliceai = gnomad, output.dir = output.dir, 

 .     bbdd = bbdd, spliceai.program = spliceai.program, reference.splice = spliceai.reference, 

 .     annotation.splice = spliceai.annotation, distance = spliceai.distance, 

 .     mask = spliceai.masked, verbose = verbose, spliceai.10k = spliceai.10k, 

 .     genome = genome)

5. assertthat::assert_that(length(spliceai.score) != 0, msg = "Transcript not listed in SpliceAI annotation file. Please provide another annotation file if you want to compute this variant")

 

OUTPUT 2

 

It worked 😉

 

looking for VariantInfo, please wait

0% completed ... correcting variant nomenclature 

10% completed ... getting variant coordinates

15% completed ... extracting bbdd information

20% completed ... getting information from gnomAD

30% completed ... getting information from flossiesdb

40% completed ... getting clinVar information

50% completed ... getting predictors information

The following RefSeq ID versions have been updatedScanning file to determine attributes.

File attributes:

  meta lines: 29

  header_line: 30

  variant count: 1

  column count: 8

Meta line 29 read in.

All meta lines processed.

gt matrix initialized.

Character matrix gt created.

  Character matrix gt rows: 1

  Character matrix gt cols: 8

  skip: 0

  nrows: 1

  row_num: 0

Processed variant: 1

All variants processed

 

Prepare transcripts

 

Performing calculations

 

Extracting amino sequence predictions

 

Writing output

60% completed ... getting loss of function information

70% completed ... getting start codon information

80% completed ... getting functional studies information

90% completed ... getting cancerhotspots information

100% completed!!

calculating the final classification , please wait 

[1] "PVS1"

[1] "PS1"

[1] "PS3_BS3"

[1] "PM1"

[1] "PM2"

[1] "PM4"

[1] "PM5"

[1] "PP2"

[1] "PP3"

[1] "BA1"

[1] "BS1"

[1] "BS2"

[1] "BP1"

[1] "BP2"

[1] "BP4"

[1] "BP7"

[1] "other"

 

 

OUTPUT 3

 

1 / 1 variants 

looking for VariantInfo, please wait

0% completed ... correcting variant nomenclature 

10% completed ... getting variant coordinates

15% completed ... extracting bbdd information

20% completed ... getting information from gnomAD

30% completed ... getting information from flossiesdb

40% completed ... getting clinVar information

Find log file: /home/jupyter/log/2024_01_22_19_17_36.518935.log

**Comment by emunte** [comment]
Great!!

I believe the issue lies in the annotation file you provided, which seems to be missing your transcript.

Regarding the example, could you please share the log file? Here is the file path: /home/jupyter/log/2024_01_22_19_17_36.518935.log

Best regards,

Eli

**Comment by gilberto-dagente** [comment]
The log file just contains one line:

 

"CDH1 c.1137+1G>A ERROR: 'length = 2' in coercion to 'logical(1)'"

 

The output if I just run it by itself (non batch) is below

 

INPUT:

eg.gene <- "CDH1"

eg.variant <- "c.1137+1G>A"

 

var.information <- vaR(gene = eg.gene, variant = eg.variant)

 

OUTPUT:

 

looking for VariantInfo, please wait

0% completed ... correcting variant nomenclature 

10% completed ... getting variant coordinates

15% completed ... extracting bbdd information

20% completed ... getting information from gnomAD

30% completed ... getting information from flossiesdb

40% completed ... getting clinVar information

Error in !is.na(page) && !is.null(page) && class(page) != "try-error": 'length = 2' in coercion to 'logical(1)'

Traceback:

 

1. vaR(gene = eg.gene, variant = eg.variant)

2. vaRinfo(gene = gene, variant = variant, NM = NM, CCDS = CCDS, 

 .     gene.specific.df = gene.specific.df, output.dir = output.dir, 

 .     remote = remote, browser = browser, spliceai.program = spliceai.program, 

 .     spliceai.genome = spliceai.genome, spliceai.reference = spliceai.reference, 

 .     spliceai.annotation = spliceai.annotation, spliceai.distance = spliceai.distance, 

 .     spliceai.masked = spliceai.masked, provean.program = provean.program, 

 .     provean.sh = provean.sh, spliceai.10k = spliceai.10k, google.search = google.search, 

 .     verbose = verbose)

3. clinVarInfo(clinvar.ids, object = variant.info, verbose = verbose)

4. clinVarTable(clinvar.ids, verbose = verbose)

5. lapply(table$url, function(g, verbose) {

.     page <- try(readUrl(g))

.     if (!is.na(page) && !is.null(page) && class(page) != "try-error" && 

 .         any(class(page[1]) != "try-error")) {

.         table.ex <- rvest::html_table(page, fill = TRUE)

.         colnames(table.ex[[4]]) <- c("Interpretation", "Review_status", 

 .             "Condition", "Submitter", "More_information", "more")

.         interpret <- table.ex[[4]][1] %>% as.data.frame() %>% 

 .             dplyr::mutate(Interpretation = purrr::map(stringr::str_split(.data$Interpretation, 

 .                 \\n <file://n> ), 1))

.         date.clin <- table.ex[[4]][1] %>% as.data.frame() %>% 

 .             dplyr::mutate(date = purrr::map(stringr::str_split(.data$Interpretation, 

 .                 "\\(|\\)"), 2))

.         review <- table.ex[[4]][2] %>% as.data.frame() %>% dplyr::mutate(review = purrr::map(stringr::str_split(.data$Review_status, 

 .             \\n <file://n> ), 1)) %>% dplyr::select("review")

.         review.mode <- table.ex[[4]][2] %>% as.data.frame() %>% 

 .             dplyr::mutate(review2 = purrr::map(stringr::str_split(.data$Review_status, 

 .                 \\n <file://n> ), 3)) %>% dplyr::select("review2")

.         table.ex[[4]][1] <- unlist(interpret$Interpretation)

.         table.ex[[4]][2] <- unlist(review)

.         table.ex[[4]][6] <- unlist(date.clin$date)

.         table.ex[[4]]$review_mode <- unlist(review.mode)

.         table.ex[[4]] <- table.ex[[4]] %>% dplyr::rowwise() %>% 

 .             dplyr::mutate(More_information = stringr::str_replace_all(.data$More_information, 

 .                 "\n", "") %>% stringr::str_replace_all("  ", 

 .                 ""), Condition = stringr::str_replace_all(.data$Condition, 

 .                 "\n", ""))

.         summary <- reviewStatus(as.data.frame(table.ex[[4]]))

.         text.ex <- rvest::html_nodes(page, "dd")

.         interpret <- stringr::str_replace_all(rvest::html_text(text.ex)[1], 

 .             "  |\\n", "")

.         status <- stringr::str_replace_all(rvest::html_text(text.ex)[2], 

 .             "  |\\n", "")

.         submissions <- stringr::str_replace_all(rvest::html_text(text.ex)[3], 

 .             "  |\\n", "")

.         mix <- data.frame(interpret = interpret, status = status, 

 .             submissions = submissions)

.         table.ex$mix <- mix

.         table.ex[["summary"]] <- summary

.         return(table.ex)

.     }

. })

6. FUN(X[[i]], ...)

**Comment by emunte** [comment]
Hi,

Apologies for the delay in addressing the issue. I appreciate your patience. It seems like the error might be due to changes in the ClinVar web interface.
Upon review, I believe the issue has been resolved. I have not encountered the error when running the code again.
If you encounter any further issues or if there's anything specific you'd like me to check, please don't hesitate to let me know.

Thank you for bringing this to my attention.

Best regards,

Eli
